export const PATH = {
  home: '/',
  fraijour: '/fraijour',
  lines: {
    heartLeaf: '/heartLeaf',
    originalArtemisia: '/originalArtemisia',
    originalHerbWormwood: '/originalHerbWormwood',
    yuzuHoney: '/yuzuHoney',
    retinCollagen3dCore: '/retinCollagen3dCore',
    proMoisture: '/proMoisture',
    biome5lacto: '/biome5lacto',
  },
  retinCollagen3dCoreLine: {
    cleansingFoam: '/retinCollagen3dCoreLine/cleansingFoam',
    toner: '/retinCollagen3dCoreLine/toner',
    eyeCream: '/retinCollagen3dCoreLine/eyeCream',
    cream: '/retinCollagen3dCoreLine/cream',
    ampouleMist: '/retinCollagen3dCoreLine/ampouleMist',
  },
  yuzuHoneyLine: {
    cleansingBalm: '/yuzuHoneyLine/cleansingBalm',
    allClearCleansingFoam: '/yuzuHoneyLine/allClearCleansingFoam',
    essentialToner: '/yuzuHoneyLine/essentialToner',
    capsuleEyeCream: '/yuzuHoneyLine/capsuleEyeCream',
    enrichedCream: '/yuzuHoneyLine/enrichedCream',
    lipSleepingMask: '/yuzuHoneyLine/lipSleepingMask',
  },
  originalHerbWormwoodLine: {
    cleansingOil: '/originalHerbWormwoodLine/cleansingOil',
    cleansingFoam: '/originalHerbWormwoodLine/cleansingFoam',
    cleansingWater: '/originalHerbWormwoodLine/cleansingWater',
    peelingGel: '/originalHerbWormwoodLine/peelingGel',
    sheetMask: '/originalHerbWormwoodLine/sheetMask',
    o2Maskpack: '/originalHerbWormwoodLine/o2Maskpack',
    calmingToner: '/originalHerbWormwoodLine/calmingToner',
    phaPeelingEssence: '/originalHerbWormwoodLine/phaPeelingEssence',
    calmingWateryCream: '/originalHerbWormwoodLine/calmingWateryCream',
  },
  biome5lactoLine: {
    balanceToner: '/biome5lactoLine/balanceToner',
    retexturizingRosyMask: '/biome5lactoLine/retexturizingRosyMask',
    balanceMoisturizer: '/biome5lactoLine/balanceMoisturizer',
    balanceGelCleanser: '/biome5lactoLine/balanceGelCleanser',
    treatmentAmpoule: '/biome5lactoLine/treatmentAmpoule',
  },
  proMoistureLine: {
    enzymePowderWash: '/proMoistureLine/enzymePowderWash',
    creamyToner: '/proMoistureLine/creamyToner',
    moistureSheetMask: '/proMoistureLine/moistureSheetMask',
    intensiveCream: '/proMoistureLine/intensiveCream',
    milkToningClayMask: '/proMoistureLine/milkToningClayMask',
  },
  heartLeafLine: {
    blemishphBalancedCleansingFoam: '/heartLeafLine/blemishphBalancedCleansingFoam',
    blemishToner: '/heartLeafLine/blemishToner',
    intensiveCalmingEssence: '/heartLeafLine/intensiveCalmingEssence',
    blemishMoistureCream: '/heartLeafLine/blemishMoistureCream',
    poreMeltingGelMask: '/heartLeafLine/poreMeltingGelMask',
  },
};
