export const PATH = {
  home: '/',
  fraijour: '/fraijour',
  lines: {
    heartLeaf: 'heartLeaf',
    originalArtemisia: 'originalArtemisia',
    originalHerbWormwood: 'originalHerbWormwood',
    yuzuHoney: 'yuzuHoney',
    retinCollagen3dCode: 'retinCollagen3dCode',
    proMoisture: 'proMoisture',
    biome5lacto: 'biome5lacto',
  },
  retinCollagen3dCodeLine: {
    сleansingFoam: 'сleansingFoam',
    toner: 'toner',
    eyeCream: 'eyeCream',
    cream: 'cream',
    ampouleMist: 'ampouleMist',
  },
  yuzuHoneyLine: {
    cleansingBalm: 'cleansingBalm',
    allClearCleansingFoam: 'allClearCleansingFoam',
    essentialToner: 'essentialToner',
    capsuleEyeCream: 'capsuleEyeCream',
    enrichedCream: 'enrichedCream',
    lipSleepingMask: 'lipSleepingMask',
  },
  originalHerbWormwoodLine: {
    cleansingOil: 'cleansingOil',
    cleansingFoam: 'cleansingFoam',
    cleansingWater: 'cleansingWater',
    peelingGel: 'peelingGel',
    sheetMask: 'sheetMask',
    o2Maskpack: 'o2Maskpack',
    calmingToner: 'calmingToner',
    phaPeelingEssence: 'phaPeelingEssence',
    calmingWateryCream: 'calmingWateryCream',
  },
  biome5lactoLine: {
    balanceGelCleanser: 'balanceGelCleanser',
    balanceToner: 'balanceToner',
    treatmentAmpoule: 'treatmentAmpoule',
    balanceMoisturizer: 'balanceMoisturizer',
  },
  proMoistureLine: {
    enzymePowderWash: 'enzymePowderWash',
    creamyToner: 'creamyToner',
    moistureSheetMask: 'moistureSheetMask',
    intensiveCream: 'intensiveCream',
  },
  heartLeafLine: {
    blemishphBalancedCleansingFoam: 'blemishphBalancedCleansingFoam',
    blemishToner: 'blemishToner',
    intensiveCalmingEssence: 'intensiveCalmingEssence',
    blemishMoistureCream: 'blemishMoistureCream',
  },
};
